// Supabase Database Types
// This file will be auto-generated by Supabase CLI once we run migrations
// For now, we define a placeholder type

export type Database = {
  public: {
    Tables: {
      // Placeholder - will be populated after migrations
      // user_profiles: {
      //   Row: { ... }
      //   Insert: { ... }
      //   Update: { ... }
      // }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'owner' | 'admin' | 'user'
      subscription_tier: 'free' | 'basic' | 'pro' | 'premium'
    }
  }
}

// Type helpers
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T]
